CREATE TABLE "C23833"."XML_PARSER_REPO" 
   (	"ID" NUMBER, 
	"NODE_NAME" VARCHAR2(100), 
	"PARENT_ID" NUMBER, 
	"PARENT_NODE_NAME" VARCHAR2(100), 
	"POSITION" NUMBER, 
	"NODE_TYPE" VARCHAR2(50), 
	"NODE_VALUE" VARCHAR2(4000), 
	"NO_CHILDREN" NUMBER, 
	"CELL_VALUE" VARCHAR2(4000), 
	"CELL_TYPE" CHAR(1)
   ) 