WITH constr AS (
    SELECT c.TABLE_NAME AS CHILD_TABLE, d.TABLE_NAME AS parent_table
    FROM   ALL_CONSTRAINTS c, ALL_CONSTRAINTS d
    WHERE  c.CONSTRAINT_TYPE = 'R'
           AND c.OWNER = 'ICE' AND c.TABLE_NAME LIKE 'CORP_CC2%'
           AND d.CONSTRAINT_NAME = c.r_CONSTRAINT_NAME
),
prt_child AS (
    SELECT OBJECT_NAME AS CHILD_TABLE, PARENT_TABLE
    FROM   ALL_OBJECTS a
           LEFT OUTER JOIN
           constr c
    ON     a.OBJECT_NAME = c.CHILD_TABLE
    WHERE  a.OBJECT_TYPE = 'TABLE' AND a.OWNER = 'ICE'
           AND a.OBJECT_NAME LIKE 'CORP_CC2%'
),
tbl_hier AS (
    SELECT CHILD_TABLE, PARENT_TABLE, 
           LEVEL AS DEPTH, 
           CONNECT_BY_ROOT CHILD_TABLE AS ROOT,
           SYS_CONNECT_BY_PATH (CHILD_TABLE, '/') FULL_PATH
    FROM prt_child 
    START WITH PARENT_TABLE IS NULL
    CONNECT BY NOCYCLE PRIOR CHILD_TABLE = PARENT_TABLE
),
max_level AS (
    SELECT CHILD_TABLE, ROOT, DEPTH,
           MAX (DEPTH) OVER (PARTITION BY CHILD_TABLE) AS MAX_DEPTH
    FROM   tbl_hier
)   SELECT DISTINCT CHILD_TABLE, MAX_DEPTH AS CREATION_ORDER
    FROM   max_level
    WHERE  DEPTH = MAX_DEPTH
    ORDER BY MAX_DEPTH, CHILD_TABLE ;
